### ISSUE TITLE
Theme demo sites are down

### ISSUE THREAD

**Issue by patrikhuber** [madoublet/respond-themes#13]
Hi!

On the marketplace (https://respondcms.com/marketplace), all "Demo" buttons seem to link to URLs that are offline - e.g. http://aspire.respond.website/.

**Comment by madoublet** [comment]
Thanks for the heads up!  I updated the links.

**Comment by patrikhuber** [comment]
Awesome!
FYI I had to do a full refresh (CTRL+F5), otherwise, the links would not update. Seems to me like it would be better if respondcms would force browsers to re-load the newest version of a page after it has been changing? Most users don't know about CTRL+F5 so I am afraid that if I make changes like this to my site, users may not see the newest version of it. Or is my fear unwarranted?

**Comment by patrikhuber** [comment]
Also, some of the templates like e.g. https://app.respondcms.com/sites/energy/ try to load http fonts & css, which doesn't work in modern browsers over https connections:

E.g.:

> Mixed Content: The page at 'https://app.respondcms.com/sites/energy/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Quicksand:300,400,700'. This request has been blocked; the content must be served over HTTPS.
csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=31.3&action=apiboot2&e=10_1_0,10_2_0&rt=main.9 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

**Comment by madoublet** [comment]
FYI, I am going to track this in the main repo:  https://github.com/madoublet/respond/issues/567
